linters:
  ColorVariable:
    enabled: false
  NameFormat:
    exclude:
      - 'assets/yelp_reveal.scss'
  MergeableSelector:
    enabled: false
  SelectorDepth:
    exclude:
      - 'assets/yelp_reveal.scss'
